# nixpacks.toml - Force Python 3.11 for original repo structure
[variables]
PYTHON_VERSION = "3.11.9"

[phases.setup]
nixPkgs = ["python311", "gcc", "pkg-config"]

[phases.install]
cmds = [
    "python --version",
    "python -m pip install --upgrade pip",
    "pip install setuptools>=68.0.0 wheel>=0.40.0",
    "pip install -r requirements.txt"
]

[start]
cmd = "python main.py"