# nixpacks.toml - Render build configuration with Python 3.11 (no Rust)
[variables]
PYTHON_VERSION = "3.11.9"

[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = [
    "python -m pip install --upgrade pip",
    "pip install setuptools>=70.0.0 wheel>=0.41.0",
    "pip install --only-binary=all -r requirements_super_minimal.txt"
]

[start]
cmd = "python main_super_minimal.py"