# nixpacks.toml - Render build configuration
[phases.setup]
nixPkgs = ["python311", "gcc", "pkg-config"]

[phases.install]
cmds = [
    "python -m pip install --upgrade pip setuptools wheel",
    "pip install -r requirements.txt"
]

[start]
cmd = "python main.py"