# render.yaml - Render deployment configuration
services:
  - type: web
    name: project-netra-backend
    env: python
    repo: https://github.com/SwapnilSonawane894/Backend-of-Project-Netra
    buildCommand: |
      python -m pip install --upgrade pip
      pip install setuptools>=70.0.0 wheel>=0.41.0
      pip install -r requirements.txt
    startCommand: python main.py
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: PORT
        value: 10000
    healthCheckPath: /